In [1]:
import numpy as np

In [4]:
#bir boyutlu numpy dizisi oluşturma
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.ndim #Boyutu

1

In [6]:
arr.shape #Şekil

(5,)

In [7]:
arr.dtype #Veri tipi

dtype('int64')

In [8]:
arr[0]

np.int64(1)

In [9]:
arr[-1]

np.int64(5)

In [10]:
arr[1:4]

array([2, 3, 4])

In [12]:
arr + 5

array([ 6,  7,  8,  9, 10])

In [15]:
arr * 2

array([ 2,  4,  6,  8, 10])

In [16]:
arr / 2

array([0.5, 1. , 1.5, 2. , 2.5])

In [17]:
arr ** 2

array([ 1,  4,  9, 16, 25])

In [18]:
#Ortalama, toplam, maksimum, minimum

In [19]:
np.sum(arr)

np.int64(15)

In [20]:
np.mean(arr)

np.float64(3.0)

In [21]:
np.max(arr)

np.int64(5)

In [23]:
np.min(arr)

np.int64(1)

In [24]:
np.std(arr)     # standart sapma

np.float64(1.4142135623730951)

In [25]:
np.var(arr)     # varyans

np.float64(2.0)

In [26]:
#eleman sayısı
arr.size

5

In [28]:
#Hazır 1D dizi oluşturma
np.arange(0, 10, 2)   # 0'dan 10'a kadar 2'şer artan

array([0, 2, 4, 6, 8])

In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.linspace(0, 1, 5)  # 0 ile 1 arasında 5 eşit sayı

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [33]:
#1D Numpy -> Python Listesine çevirme
arr.tolist()

[1, 2, 3, 4, 5]

In [34]:
arr = np.array([10, 20, 30, 40, 50])

arr[arr > 30]     # 30'dan büyükleri getir

array([40, 50])

In [35]:
arr[arr % 20 == 0] # 20'ye tam bölünenler

array([20, 40])

In [36]:
#Rastgele sayılarla 1D array
np.random.randint(0, 100, 5)

array([57, 43, 81, 33, 25], dtype=int32)

In [37]:
np.random.rand(5)     # 0-1 arası

array([0.0398573 , 0.86753676, 0.11052367, 0.73325179, 0.19692278])

In [38]:
#Örnek uygulama öğrenci analizi
notlar = np.array([75, 82, 90, 67, 88, 92, 58])

print("Ortalama:", np.mean(notlar))
print("Maks:", np.max(notlar))
print("Başarılı (>80):", notlar[notlar > 80])

Ortalama: 78.85714285714286
Maks: 92
Başarılı (>80): [82 90 88 92]
