In [1]:
import numpy as np

mat = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
#Temel Özellikler
mat.ndim      # boyut sayısı → 2

2

In [3]:
mat.shape     # (satır, sütun)

(2, 3)

In [4]:
mat.size      # toplam eleman sayısı

6

In [5]:
mat.dtype     # veri tipi

dtype('int64')

In [6]:
#Elemanlara erişim İndexing
mat[0, 1]   # 1. satır, 2. sütun → 2

np.int64(2)

In [7]:
#Bir Satırı Alma
mat[1]      # [4, 5, 6]

array([4, 5, 6])

In [8]:
#Bir Sütunu Alma
mat[:, 1]   # ikinci sütun

array([2, 5])

In [9]:
#Dilimleme (Slicing)
mat[0:2, 0:2]   # ilk 2 satır, ilk 2 sütun

array([[1, 2],
       [4, 5]])

In [10]:
mat ** 2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
#Satır bazlı / sütun bazlı işlemler
np.sum(mat, axis=0)   # sütun toplamları

array([5, 7, 9])

In [12]:
np.sum(mat, axis=1)   # satır toplamları

array([ 6, 15])

In [14]:
#Matris Çarpımı (Matrix Multiplication)

#Bu çok önemli: * element-wise çarpar,
#@ veya np.dot() matris çarpımı yapar.

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

A * B      # element-wise

array([[ 5, 12],
       [21, 32]])

In [15]:
A @ B      # matris çarpımı

array([[19, 22],
       [43, 50]])

In [16]:
np.dot(A, B)  # aynı

array([[19, 22],
       [43, 50]])

In [17]:
#Hazır Fonksiyonlarla Matris Oluşturma
np.zeros((3, 4))   # 3x4 matris

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.ones((2, 2))

array([[1., 1.],
       [1., 1.]])

In [19]:
#arange + reshape
np.arange(1, 13).reshape(3, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
mat.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
#Dizileri Birleştirme (Stacking)
#Dikey birleştirme (satır ekleme)
np.vstack([mat, [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
#Yatay birleştirme (sütun ekleme)
np.hstack([mat, [[10], [11]]])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11]])

In [24]:
#Boolean Masking (2D Filtreleme)
mat[mat > 3]        # 3’ten büyük elemanları alır
#Sonuç 1D array olur.

array([4, 5, 6])

In [25]:
# Günün 4 zamanında 3 farkli şehrin sıcaklığı
temp = np.array([
    [10, 12, 15],   # sabah
    [18, 20, 22],   # öğlen
    [16, 17, 19],   # akşam
    [12, 11, 13]    # gece
])

print("Sütun ortalamaları (şehir ortalamaları):", temp.mean(axis=0))
print("Satır ortalamaları (gün içi ortalama):", temp.mean(axis=1))
print("En yüksek:", temp.max())
print("Öğlen sıcaklıkları:", temp[1])

Sütun ortalamaları (şehir ortalamaları): [14.   15.   17.25]
Satır ortalamaları (gün içi ortalama): [12.33333333 20.         17.33333333 12.        ]
En yüksek: 22
Öğlen sıcaklıkları: [18 20 22]
